POST http://localhost:3003/api/blogs/6943f29135e9d7b5e1fcce43/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzc2RmIiwiaWQiOiI2OTE1NzVlZGEzZmFlMjhlOWJhOWZlMDgiLCJpYXQiOjE3NjMxMDM1NjB9.U9UI5S6bw9w_iQ8fnbe8bKggYD-oQZeWdjNC4MZW-1w

{
  "comment": "hello3"
}
