DELETE http://localhost:3003/api/blogs/69425389083099b2b1a66476
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlvdWRhbyIsImlkIjoiNjkxYzBjZTU3NWY1MzgzYTkwYTU5YjYwIiwiaWF0IjoxNzY2MTA1MjM1LCJleHAiOjE3NjYxMDg4MzV9.qZ1jdCbe1-8cGnRN5MaxUizyTeg23AWlYINQDE2tBHc
